/*
 * Users API
 *
 * An API for managing system users
 *
 * API version: 2.0.0
 * Contact: joe@jjssoftware.co.uk
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	sw "github.com/jjssoftware/go-user-api/go"
	"log"
	"net/http"
)

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
