/*
 * Users API
 *
 * An API for managing system users
 *
 * API version: 1.0.0
 * Contact: joe@jjssoftware.co.uk
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type User struct {

	UserName string `json:"userName"`

	FirstName string `json:"firstName"`

	Surname string `json:"surname"`

	Id int32 `json:"id"`

	UniqueId string `json:"uniqueId"`

	CreateTimestamp time.Time `json:"createTimestamp"`
}
