/*
 * Users API
 *
 * An API for managing system users
 *
 * API version: 1.0.0
 * Contact: joe@jjssoftware.co.uk
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/jjssoftware/User_API/1.0.0/",
		Index,
	},

	Route{
		"AddUser",
		strings.ToUpper("Put"),
		"/jjssoftware/User_API/1.0.0/addUser",
		AddUser,
	},

	Route{
		"AuthenticateUser",
		strings.ToUpper("Post"),
		"/jjssoftware/User_API/1.0.0/authenticate",
		AuthenticateUser,
	},

	Route{
		"GetUserByUserId",
		strings.ToUpper("Get"),
		"/jjssoftware/User_API/1.0.0/getUser/{userId}",
		GetUserByUserId,
	},

	Route{
		"GetUserByUserName",
		strings.ToUpper("Get"),
		"/jjssoftware/User_API/1.0.0/getUser/{userName}",
		GetUserByUserName,
	},
}
