/*
 * User API
 *
 * An API for managing system users
 *
 * API version: 1.0.3
 * Contact: joe@jjssoftware.co.uk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"net/http"
)

// UserAPIApiRouter defines the required methods for binding the api requests to a responses for the UserAPIApi
// The UserAPIApiRouter implementation should parse necessary information from the http request,
// pass the data to a UserAPIApiServicer to perform the required actions, then write the service results to the http response.
type UserAPIApiRouter interface {
	AddUser(http.ResponseWriter, *http.Request)
	AuthenticateUser(http.ResponseWriter, *http.Request)
	GetUserByUserId(http.ResponseWriter, *http.Request)
	GetUserByUserName(http.ResponseWriter, *http.Request)
}

// UserAPIApiServicer defines the api actions for the UserAPIApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type UserAPIApiServicer interface {
	AddUser(context.Context, NewUser) (ImplResponse, error)
	AuthenticateUser(context.Context, UserCredentials) (ImplResponse, error)
	GetUserByUserId(context.Context, int32) (ImplResponse, error)
	GetUserByUserName(context.Context, string) (ImplResponse, error)
}
