/*
 * User API
 *
 * An API for managing system users
 *
 * API version: 1.0.3
 * Contact: joe@jjssoftware.co.uk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

//Implementation response defines an error code with the associated body
type ImplResponse struct {
	Code int
	Body interface{}
}
