/*
 * User API
 *
 * An API for managing system users
 *
 * API version: 1.0.3
 * Contact: joe@jjssoftware.co.uk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type UserCredentials struct {

	Username string `json:"username,omitempty"`

	Password string `json:"password"`
}
