name: test-action

on: push

jobs:  
  file_existence:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v1
      - name: Check for existence of the ./definition/api.yaml API definition file
        uses: andstor/file-existence-action@v1
        with:
          files: "./definition/api.yaml"
        env: 
          API_EXISTS: steps.check_files.outputs.files_exists == 'true'                   
  
  build:    
    runs-on: ubuntu-latest    
    steps:    
      - uses: actions/checkout@v2    
        if: env.API_EXISTS
      - name: Set up JDK 1.8      
        uses: actions/setup-java@v1
        with: 
          java-version: 1.8
        if: env.API_EXISTS
      - name: Get a local copy of the built open api generator
        uses: wei/wget@v1
        with:
          args: https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.0.1/openapi-generator-cli-5.0.1.jar -O openapi-generator-cli.jar
        if: env.API_EXISTS        
      - name: List the contents of the workflow action working dir
        working-directory: ${{ github.workspace }}
        run: ls -la        
      - name: Execute code gen
        if: env.API_EXISTS
        run: java -jar ./openapi-generator-cli.jar generate ./definition/api.yaml -l go-server -o ./ -DpackageName=api
