name: actions

on:
  push:
    paths:
    - 'definition/*.yaml'

jobs:
  codegen-go-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup the latest openapi-generator-cli
        shell: bash
        run: curl https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/bin/utils/openapi-generator-cli.sh > ./openapi-generator-cli && chmod u+x ./openapi-generator-cli
      - name: List the contents of the workflow action working dir
        shell: bash
        run: ls -la
      - name: Execute code gen
        run: ./openapi-generator-cli generate -i ./definition/api.yaml -g go-server -o ./ -ppackageName=api --git-user-id=jjssoftware --git-repo-id=go-user-api
      - name: List the contents of the workflow action working dir
        run: ls -la
      - name: Commit generated code
        shell: bash
        run: git config --global user.email "joe@jjssoftware.co.uk" && git config --global user.name "Joe" && git fetch --all && git add -A && git commit -m "automated codegen commit" && git pull --rebase && git push --force
