name: test-action

on: push

jobs:            
  build:    
    runs-on: ubuntu-latest    
    steps:    
      - uses: actions/checkout@v2    
      - name: Set up JDK 1.8      
        uses: actions/setup-java@v1
        with: 
          java-version: 1.8
      - name: Get a local copy of the built open api generator
        uses: wei/wget@v1
        with:
          args: https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.0.1/openapi-generator-cli-5.0.1.jar -O openapi-generator-cli.jar
      - name: List the contents of the workflow action working dir
        working-directory: ${{ github.workspace }}
        run: ls -la        
      - name: Execute code gen
        run: java -jar ./openapi-generator-cli.jar generate -i ./definition/api.yaml -g go-server -o ./ -ppackageName=api
      - name: List the contents of the workflow action working dir
        working-directory: ${{ github.workspace }}
        run: ls -la
      - name: Commit generated code
        run: chmod u+x ./git_push.sh && ./git_push.sh
